apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mesyrob/homelab-k8s
    targetRevision: HEAD
    path: manifests/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
