apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: audiobookshelf-config
  namespace: audiobookshelf
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: audiobookshelf-data
  namespace: audiobookshelf
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
